#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

apt-fast dist-upgrade -y
aptitude dist-upgrade -y -o APT::Get::Fix-Missing=true
apt autoremove
aptitude autoclean -y
snap refresh
